/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 18 09:55:57 GMT 2022
 */

package sg.edu.nus.comp.cs4218.impl.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.junit.jupiter.api.extension.RegisterExtension;
import sg.edu.nus.comp.cs4218.impl.app.EchoApplication;

@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class EchoApplication_ESTest extends EchoApplication_ESTest_scaffolding {
@RegisterExtension
  static EvoRunnerJUnit5 runner = new EvoRunnerJUnit5(EchoApplication_ESTest.class);

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      EchoApplication echoApplication0 = new EchoApplication();
      String[] stringArray0 = new String[9];
      byte[] byteArray0 = new byte[5];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, 1569, 1);
      try { 
        echoApplication0.run(stringArray0, byteArrayInputStream0, (OutputStream) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // echo: OutputStream not provided
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.EchoApplication", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      EchoApplication echoApplication0 = new EchoApplication();
      String[] stringArray0 = new String[3];
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("sg.edu.nus.comp.cs4218.impl.app.EchoApplication", true);
      echoApplication0.run(stringArray0, (InputStream) null, mockFileOutputStream0);
      assertEquals(3, stringArray0.length);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      EchoApplication echoApplication0 = new EchoApplication();
      String[] stringArray0 = new String[0];
      String string0 = echoApplication0.constructResult(stringArray0);
      assertEquals("\n", string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test3()  throws Throwable  {
      EchoApplication echoApplication0 = new EchoApplication();
      try { 
        echoApplication0.constructResult((String[]) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // echo: Null arguments
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.EchoApplication", e);
      }
  }
}
