/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 18 10:02:58 GMT 2022
 */

package sg.edu.nus.comp.cs4218.impl.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.jupiter.api.extension.RegisterExtension;
import sg.edu.nus.comp.cs4218.impl.app.PasteApplication;

@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class PasteApplication_ESTest extends PasteApplication_ESTest_scaffolding {
@RegisterExtension
  static EvoRunnerJUnit5 runner = new EvoRunnerJUnit5(PasteApplication_ESTest.class);

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test00()  throws Throwable  {
      PasteApplication pasteApplication0 = new PasteApplication();
      byte[] byteArray0 = new byte[3];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      Boolean boolean0 = Boolean.FALSE;
      String string0 = pasteApplication0.mergeStdin(boolean0, byteArrayInputStream0);
      assertEquals("\u0000\u0000\u0000", string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test01()  throws Throwable  {
      PasteApplication pasteApplication0 = new PasteApplication();
      Boolean boolean0 = Boolean.valueOf(true);
      String[] stringArray0 = new String[9];
      stringArray0[0] = "";
      stringArray0[1] = "Exception Caught";
      byte[] byteArray0 = new byte[0];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      String string0 = pasteApplication0.mergeFileAndStdin(boolean0, byteArrayInputStream0, stringArray0);
      assertEquals("paste: Exception Caught: : No such file or directory", string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test02()  throws Throwable  {
      PasteApplication pasteApplication0 = new PasteApplication();
      Boolean boolean0 = Boolean.FALSE;
      byte[] byteArray0 = new byte[3];
      String[] stringArray0 = new String[0];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      String string0 = pasteApplication0.mergeFileAndStdin(boolean0, byteArrayInputStream0, stringArray0);
      assertEquals("", string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test03()  throws Throwable  {
      PasteApplication pasteApplication0 = new PasteApplication();
      Boolean boolean0 = Boolean.valueOf(false);
      String[] stringArray0 = new String[1];
      try { 
        pasteApplication0.mergeFileAndStdin(boolean0, (InputStream) null, stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test04()  throws Throwable  {
      PasteApplication pasteApplication0 = new PasteApplication();
      Boolean boolean0 = Boolean.valueOf(true);
      String[] stringArray0 = new String[9];
      stringArray0[0] = "";
      byte[] byteArray0 = new byte[0];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      try { 
        pasteApplication0.mergeFileAndStdin(boolean0, byteArrayInputStream0, stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test05()  throws Throwable  {
      PasteApplication pasteApplication0 = new PasteApplication();
      Boolean boolean0 = Boolean.valueOf((String) null);
      try { 
        pasteApplication0.mergeFile(boolean0, (String[]) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Exception Caught
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.PasteApplication", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test06()  throws Throwable  {
      PasteApplication pasteApplication0 = new PasteApplication();
      byte[] byteArray0 = new byte[3];
      Boolean boolean0 = Boolean.TRUE;
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      String string0 = pasteApplication0.mergeStdin(boolean0, byteArrayInputStream0);
      assertEquals("\u0000\u0000\u0000", string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test07()  throws Throwable  {
      PasteApplication pasteApplication0 = new PasteApplication();
      try { 
        pasteApplication0.mergeStdin((Boolean) null, (InputStream) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Null Pointer Exception
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.PasteApplication", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test08()  throws Throwable  {
      PasteApplication pasteApplication0 = new PasteApplication();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PipedInputStream pipedInputStream0 = new PipedInputStream(pipedOutputStream0, 4232);
      String[] stringArray0 = new String[5];
      stringArray0[0] = "Exception Caught";
      stringArray0[1] = "Null Pointer Exception";
      stringArray0[2] = "Exception Caught";
      stringArray0[3] = "Null Pointer Exception";
      stringArray0[4] = "Null Pointer Exception";
      pasteApplication0.run(stringArray0, pipedInputStream0, pipedOutputStream0);
      assertEquals(53, pipedInputStream0.available());
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test09()  throws Throwable  {
      PasteApplication pasteApplication0 = new PasteApplication();
      String[] stringArray0 = new String[2];
      InputStream inputStream0 = InputStream.nullInputStream();
      try { 
        pasteApplication0.run(stringArray0, inputStream0, (OutputStream) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // paste: Null Pointer Exception
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.PasteApplication", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test10()  throws Throwable  {
      PasteApplication pasteApplication0 = new PasteApplication();
      byte[] byteArray0 = new byte[0];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, 2, (-2080418860));
      MockFile mockFile0 = new MockFile("..");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      String[] stringArray0 = new String[0];
      pasteApplication0.run(stringArray0, byteArrayInputStream0, mockPrintStream0);
      assertEquals(0, stringArray0.length);
  }
}
